### ISSUE TITLE
Which plotting library should we use?

### ISSUE THREAD

**Issue by dwinkler1** [danielw2904/mixtape#2]
Those come to mind:
https://docs.juliaplots.org/latest/ + https://github.com/JuliaPlots/StatsPlots.jl
https://gadflyjl.org/stable/
https://www.queryverse.org/VegaLite.jl/stable/

**Comment by akulumbeg** [comment]
The plots in the R version are quite rudimentary and given that they are built on ggplot anyway, perhaps Gadfly would be a good choice?

**Comment by dwinkler1** [comment]
I tried out some libraries and created a topic on discourse https://discourse.julialang.org/t/plotting-library-for-online-tutorial-book/61915

**Comment by dwinkler1** [comment]
> The plots in the R version are quite rudimentary and given that they are built on ggplot anyway, perhaps Gadfly would be a good choice?

Gadfly is quite nice! I worry that it is not very flexible compared to plots. But neither is ggplot so maybe thats fine
