### ISSUE TITLE
Project vs Standalone Files

### ISSUE THREAD

**Issue by akulumbeg** [danielw2904/mixtape#6]
In the original, each of the files is a standalone file (all modules/libraries are called in the beginning of each files). I would consider keeping it this way in the Julia translation as well to not confuse language newbies with loading a module with preloaded libs and data reading function.
I know it is tedious to always write this out everytime and that the module helps, but I think that there is a reason why the files are standalone in the original, so it might be a good idea to stick to this style (?).

Edit: The Python translation by some volunteers is also like this.

**Comment by dwinkler1** [comment]
You are probably correct but I don't want to admit that.

**Comment by akulumbeg** [comment]
Time to swallow your pride, my friend 😄
